---
- name: Append hosts
  blockinfile:
    dest: ~/.config/hosts
    backup: yes
    block: |
      {{ item.content }}
    marker: ""
  with_items:
    - "{{ minio }}"
    - "{{ alw-03 }}"
  changed_when: true
